global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Controls.Metadata;
global using Avalonia.Controls.Presenters;
global using Avalonia.Controls.Primitives;
global using Avalonia.Controls.Templates;
global using Avalonia.Input;
global using Avalonia.Interactivity;
global using Avonic.Components.Controls.Enums;